version: '3'
services:
  db:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: product_db
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    volumes:
      - ./pg_data:/var/lib/postgresql/data/pgdata

  pgAdmin:
    container_name: pg_admin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 123
    volumes:
      - pgAdmin:/var/lib/pgadmin
    ports:
      - 8888:80
    depends_on:
      - db

  app:
    container_name: iPrody-Devs-Gr0000000008-product-service
    build:
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      POSTGRES_HOST: db
    restart: always
    depends_on:
      - db
      - pgAdmin

volumes:
  pg_data:
  pgAdmin: